# Generated by Django 5.0.6 on 2024-06-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
