# Generated by Django 5.0.6 on 2024-06-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='name',
        ),
    ]
